# Generated by Django 3.2.5 on 2021-08-02 10:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_auto_20210731_1129'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0005_alter_organization_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('slug', models.SlugField(unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت کننده')),
                ('organization_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization', verbose_name='انتخاب سازمان')),
            ],
            options={
                'verbose_name': 'پیش فاکتور',
                'verbose_name_plural': 'پیش فاکتور ها',
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('discount', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='انتخاب دستگاه')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quote.quote', verbose_name='پیش فاکتور')),
            ],
            options={
                'verbose_name': 'دستگاه مورد درخواست',
                'verbose_name_plural': 'دستگاه های مورد درخواست',
            },
        ),
    ]
