# Generated by Django 3.2.5 on 2021-08-06 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20210804_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='price',
        ),
    ]
