# Generated by Django 3.2.5 on 2021-07-26 12:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_auto_20210726_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('name', models.CharField(max_length=100, verbose_name='نام سازمان')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='phone number invalid', regex='^[0][9]\\d{9}$')], verbose_name='تلفن')),
                ('number_of_employees', models.PositiveIntegerField(max_length=4, verbose_name='تعداد کارمندان')),
                ('audience_full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی مخاطب')),
                ('audience_phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='phone number invalid', regex='^[0][9]\\d{9}$')], verbose_name='تلفن مخاطب')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization_product', models.ManyToManyField(to='product.OrganizationProduct', verbose_name='محصولات تولیدی')),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان ها',
            },
        ),
    ]
