# Generated by Django 3.2.5 on 2021-07-27 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20210727_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='audience_phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره اشتباه است.', regex='^[0][9]\\d{9}$')], verbose_name='تلفن مخاطب'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره اشتباه است.', regex='^0\\d{2,3}-\\d{8}$')], verbose_name='تلفن سازمان'),
        ),
    ]
