# Generated by Django 3.2.5 on 2021-07-28 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20210727_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره اشتباه است.', regex='^0[0-9]{2,}[0-9]{7,}$')], verbose_name='تلفن سازمان'),
        ),
    ]
