# Generated by Django 3.2.5 on 2021-07-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول تولیدی')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت محصول')),
                ('tax', models.BooleanField(verbose_name='آیا مشمول مالیات است؟')),
                ('catalogue_pdf', models.FileField(upload_to='catalogue_pdf', verbose_name='فایل pdf کاتالوگ')),
                ('catalogue_image', models.ImageField(upload_to='catalogue_image', verbose_name='عکس کاتالوگ')),
                ('technical_features', models.TextField(verbose_name='ویژگی های فنی')),
            ],
        ),
    ]
