# Generated by Django 3.2.5 on 2021-07-25 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_can_use_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalogue_pdf',
            field=models.FileField(upload_to='catalogue_pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='فایل pdf کاتالوگ'),
        ),
    ]
