# Generated by Django 3.2.5 on 2021-07-25 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_catalogue_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalogue_pdf',
            field=models.FileField(help_text='فقط فایل pdf قلبل قبول است', upload_to='catalogue_pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='فایل pdf کاتالوگ'),
        ),
    ]
