# Generated by Django 3.2.5 on 2021-07-25 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_catalogue_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalogue_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalogue_image', verbose_name='عکس کاتالوگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalogue_pdf',
            field=models.FileField(blank=True, help_text='pdf :فرمت های قابل قبول', null=True, upload_to='catalogue_pdf', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='کاتالوگ pdf'),
        ),
    ]
