# Generated by Django 3.2.5 on 2021-07-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210725_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationproduct',
            options={'verbose_name': 'محصول تولیدی', 'verbose_name_plural': 'محصولات تولیدی'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
