# Generated by Django 3.2.5 on 2021-07-31 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210726_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catalogue_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس کاتالوگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalogue_pdf',
            field=models.FileField(blank=True, help_text='فرمت pdf قابل قبول است', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='کاتالوگ pdf'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت محصول (تومان)'),
        ),
    ]
