# Generated by Django 3.2.5 on 2021-08-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailhistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailhistory',
            name='email_status',
            field=models.BooleanField(default=False, verbose_name='وضعیت ایمیل'),
        ),
    ]
