# Generated by Django 3.2.5 on 2021-08-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followup',
            old_name='organization',
            new_name='organization_name',
        ),
    ]
